### ISSUE TITLE
Deployment Strategy Issue

### ISSUE THREAD

**Issue by No9** [tremor-rs/tremor-k8s-helm#3]
Hey All 
There seems to be an issue with the deployment definition.
When I run the install with the following versions
```
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", 
GitTreeState:"dirty", GoVersion:"go1.15.7"}

$ oc version
Server Version: 4.6.28
Kubernetes Version: v1.19.0+d856161
```
I get the following error 
```
$ helm install tremor-install charts/tremor --create-namespace --namespace tremor
Error: unable to build kubernetes objects from release manifest: 
error validating "": error validating data: ValidationError(Deployment.spec): 
unknown field "updateStrategy" in io.k8s.api.apps.v1.DeploymentSpec
```

According to the k8s spec this line
https://github.com/tremor-rs/tremor-k8s-helm/blob/main/charts/tremor/templates/deployment.yaml#L41 
Should be set to `strategy`
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy 

I've made the change and the install completes.
If you agree it's a bug I'm happy to make a PR

**Comment by darach** [comment]
Hey Anton, nice catch!

**Comment by njegosrailic** [comment]
Hey Anton, 

Thank you. You are right. Seems like I copied this from a DeamonSet template and haven't tested it properly. 

I'll put a PR to address this.
