### ISSUE TITLE
Openshift Deployment Discussion

### ISSUE THREAD

**Issue by No9** [tremor-rs/tremor-k8s-helm#4]
Hey Again 

The default SecurityContext settings in values.yaml sets the runAsUser to 1000.
https://github.com/tremor-rs/tremor-k8s-helm/blob/main/charts/tremor/values.yaml#L136

This causes the following error in an OpenShift Deployment.
```
pods "tremor-install-6d9b6f6456-" is forbidden: 
unable to validate against any security context constraint: 
[spec.containers[0].securityContext.runAsUser: 
Invalid value: 1000: must be in the ranges: [1000660000, 1000669999]]
```
This is because each namespace/project in OpenShift has an allocation of UIDs.
`1000660000, 1000669999` in this case.

OpenShift by default will set the correct nonroot userid by default so the option doesn't need to be supplied in that scenario.

A side effect of this is that a user may try to resolve this by allowing the pod to run as a privileged user which is not a desirable outcome.

Would you be open to adding an isOpenShift variable to the values.yaml and if it is set to true a conditional in the template will unset the runAsUser property?

Also other projects I have worked on have set the following securityContext properties
```
allowPrivilegeEscalation: false
runAsNonRoot: true
```
Can I suggest we add those to the template as well?

**Comment by darach** [comment]
Hey Anton, this is a great insight / enhancement request and we'll look into it tomorrow. Thanks for going the extra mile and teaching us about OpenShift so we can make this OS compatible 👌

**Comment by njegosrailic** [comment]
Hey,

I have created PR with a few improvements. The values in values.yaml file are just default and you can override them without changing the helm chart. 

You can just simply comment out the [line](https://github.com/tremor-rs/tremor-k8s-helm/pull/5/files#diff-f6208223d08cd9b3fcf9e5ffaa3f8bb0f714a1f841b362b188ae51d2117b4d20R145) and it won't set  `runAsUser` option.

I have tested that:

```
...

       mountPath: /etc/tremor/config
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          resources:

... 
```
Would that work for you?

Thank you
